let map, blastMarker, userMarker, circleRadio, currentData = null;
const DEFAULT_PLAN='plano-voladura.png';
const DEFAULT_DATA={blastName:'Voladura Atocongo',utmX:292925.533,utmY:8651156.600,zone:18,hemisphere:'S',radiusMeters:600,date:'2026-06-02',time:'12:45',planDataUrl:DEFAULT_PLAN};

function b64urlEncode(str){return btoa(unescape(encodeURIComponent(str))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlDecode(str){str=str.replace(/-/g,'+').replace(/_/g,'/'); while(str.length%4) str+='='; return decodeURIComponent(escape(atob(str)))}
function dataFromHash(){try{const h=location.hash||'';const m=h.match(/data=([^&]+)/);if(!m)return DEFAULT_DATA;return JSON.parse(b64urlDecode(m[1]));}catch(e){return DEFAULT_DATA;}}

function utmToLatLon(easting,northing,zoneNumber,hemisphere){
  const a=6378137.0,eccSquared=0.00669438,k0=0.9996,eccPrimeSquared=eccSquared/(1-eccSquared),e1=(1-Math.sqrt(1-eccSquared))/(1+Math.sqrt(1-eccSquared));
  let x=easting-500000.0,y=northing;if(hemisphere==='S')y-=10000000.0;
  const longOrigin=(zoneNumber-1)*6-180+3,M=y/k0,mu=M/(a*(1-eccSquared/4-3*eccSquared*eccSquared/64-5*Math.pow(eccSquared,3)/256));
  const phi1Rad=mu+(3*e1/2-27*Math.pow(e1,3)/32)*Math.sin(2*mu)+(21*e1*e1/16-55*Math.pow(e1,4)/32)*Math.sin(4*mu)+(151*Math.pow(e1,3)/96)*Math.sin(6*mu);
  const N1=a/Math.sqrt(1-eccSquared*Math.sin(phi1Rad)**2),T1=Math.tan(phi1Rad)**2,C1=eccPrimeSquared*Math.cos(phi1Rad)**2,R1=a*(1-eccSquared)/Math.pow(1-eccSquared*Math.sin(phi1Rad)**2,1.5),D=x/(N1*k0);
  let lat=phi1Rad-(N1*Math.tan(phi1Rad)/R1)*(D**2/2-(5+3*T1+10*C1-4*C1**2-9*eccPrimeSquared)*D**4/24+(61+90*T1+298*C1+45*T1**2-252*eccPrimeSquared-3*C1**2)*D**6/720);
  lat=lat*180/Math.PI;
  let lon=(D-(1+2*T1+C1)*D**3/6+(5-2*C1+28*T1-3*C1**2+8*eccPrimeSquared+24*T1**2)*D**5/120)/Math.cos(phi1Rad);
  lon=longOrigin+lon*180/Math.PI;
  return [lat,lon];
}

function initMap(){map=L.map('map',{zoomControl:true}).setView([-12.218,-76.923],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:22,attribution:'&copy; OpenStreetMap'}).addTo(map);setTimeout(()=>map.invalidateSize(),300);}
function drawData(d){const [lat,lon]=utmToLatLon(Number(d.utmX),Number(d.utmY),Number(d.zone),d.hemisphere);const center=L.latLng(lat,lon);if(blastMarker)map.removeLayer(blastMarker);if(circleRadio)map.removeLayer(circleRadio);blastMarker=L.marker(center).addTo(map).bindPopup('Punto de voladura');circleRadio=L.circle(center,{radius:Number(d.radiusMeters),color:'red',fillColor:'red',fillOpacity:.13,weight:3}).addTo(map);map.fitBounds(circleRadio.getBounds(),{padding:[25,25]});setTimeout(()=>map.invalidateSize(),300);}
function renderPlan(d){const box=document.getElementById('planContainer');if(!box)return;box.innerHTML='';const img=document.createElement('img');img.src=d.planDataUrl||DEFAULT_PLAN;img.alt='Plano de referencia';box.appendChild(img);}
function viewerData(d){document.getElementById('vNombre').textContent=d.blastName||'-';document.getElementById('vFechaHora').textContent=(d.date||'-')+' / '+(d.time||'-');document.getElementById('vRadio').textContent=(d.radiusMeters||'-')+' m';}
function evaluar(){if(!userMarker||!circleRadio)return;const dist=userMarker.getLatLng().distanceTo(circleRadio.getLatLng()),r=Number(currentData.radiusMeters);const res=document.getElementById('resultado'),det=document.getElementById('detalle');res.className='resultado';if(dist<=r){res.classList.add('peligro');res.textContent='🔴 DENTRO DEL RADIO'}else{res.classList.add('ok');res.textContent='🟢 FUERA DEL RADIO'}det.textContent='Distancia aproximada: '+Math.round(dist)+' m. Radio: '+r+' m.';}
function gps(){if(!navigator.geolocation){alert('Tu navegador no soporta GPS.');return}document.getElementById('resultado').className='resultado neutral';document.getElementById('resultado').textContent='Buscando ubicación GPS...';navigator.geolocation.getCurrentPosition(pos=>{const ll=L.latLng(pos.coords.latitude,pos.coords.longitude);if(userMarker)map.removeLayer(userMarker);userMarker=L.circleMarker(ll,{radius:9,color:'#2563eb',fillColor:'#2563eb',fillOpacity:.95}).addTo(map).bindPopup('Mi ubicación GPS').openPopup();evaluar();map.fitBounds(L.featureGroup([blastMarker,userMarker,circleRadio]).getBounds(),{padding:[35,35]});document.getElementById('map').scrollIntoView({behavior:'smooth',block:'center'});},err=>{document.getElementById('resultado').className='resultado peligro';document.getElementById('resultado').textContent='No se pudo obtener la ubicación.';document.getElementById('detalle').textContent='Revisa permisos de GPS y HTTPS.';},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
function adminData(){return{blastName:document.getElementById('blastName').value,utmX:Number(document.getElementById('utmX').value),utmY:Number(document.getElementById('utmY').value),zone:Number(document.getElementById('zone').value),hemisphere:document.getElementById('hemisphere').value,radiusMeters:Number(document.getElementById('radiusMeters').value),date:document.getElementById('date').value,time:document.getElementById('time').value,planDataUrl:(currentData&&currentData.planDataUrl)||DEFAULT_PLAN};}
function setAdminDefaults(){const d=DEFAULT_DATA;currentData=d;['blastName','utmX','utmY','zone','radiusMeters','date','time'].forEach(id=>document.getElementById(id).value=d[id]);document.getElementById('hemisphere').value=d.hemisphere;}
function compressImage(file,maxW=1100,quality=.72){return new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const scale=Math.min(1,maxW/img.width),w=Math.round(img.width*scale),h=Math.round(img.height*scale);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality));};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file);});}
async function handleFile(e){const f=e.target.files[0];if(!f)return;currentData=adminData();currentData.planDataUrl=await compressImage(f);renderPlan(currentData);}
function preview(){currentData=adminData();drawData(currentData);renderPlan(currentData);}
function generateLink(){currentData=adminData();const data=b64urlEncode(JSON.stringify(currentData));const base=location.href.replace(/admin\.html.*/,'index.html').replace(/\#.*/,'');const link=base+'#data='+data;document.getElementById('publicLink').value=link;if(link.length>7500)alert('El enlace es muy largo. Usa una imagen del plano más liviana o una captura reducida.');}
async function copyLink(){const val=document.getElementById('publicLink').value;if(!val){alert('Primero genera el enlace.');return}try{await navigator.clipboard.writeText(val);alert('Enlace copiado.')}catch(e){alert('Copia manualmente el enlace.')}}
function boot(){initMap();if(document.body.dataset.mode==='admin'){document.getElementById('date').value=new Date().toISOString().slice(0,10);setAdminDefaults();drawData(currentData);renderPlan(currentData);document.getElementById('planFile').addEventListener('change',handleFile);document.getElementById('btnPreview').addEventListener('click',preview);document.getElementById('btnLink').addEventListener('click',generateLink);document.getElementById('btnCopy').addEventListener('click',copyLink);}else{currentData=dataFromHash();viewerData(currentData);drawData(currentData);renderPlan(currentData);document.getElementById('btnGPS').addEventListener('click',gps);}}
window.addEventListener('load',boot);window.addEventListener('resize',()=>map&&map.invalidateSize());