let map, blastMarker, userMarker, circleEquipos, circlePersonal, currentData=null, selectedPlanUrl='plano-voladura.png';
const DEFAULT_PLAN='plano-voladura.png';
const DEFAULT_DATA={blastName:'Voladura Atocongo',utmX:292925.533,utmY:8651156.600,zone:18,hemisphere:'S',radiusEquipos:300,radiusPersonal:500,date:'2026-06-02',time:'12:45',planDataUrl:DEFAULT_PLAN,planMime:'image/png'};
function enc(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function dec(str){str=str.replace(/-/g,'+').replace(/_/g,'/');while(str.length%4)str+='=';return JSON.parse(decodeURIComponent(escape(atob(str))))}
function dataFromHash(){try{const m=(location.hash||'').match(/data=([^&]+)/);return m?dec(m[1]):DEFAULT_DATA}catch(e){return DEFAULT_DATA}}
function utmToLatLon(easting,northing,zoneNumber,hemisphere){const a=6378137.0,e=0.00669438,k0=0.9996,ep=e/(1-e),e1=(1-Math.sqrt(1-e))/(1+Math.sqrt(1-e));let x=easting-500000,y=northing;if(hemisphere==='S')y-=10000000;const lo=(zoneNumber-1)*6-180+3,M=y/k0,mu=M/(a*(1-e/4-3*e*e/64-5*Math.pow(e,3)/256));const p=mu+(3*e1/2-27*Math.pow(e1,3)/32)*Math.sin(2*mu)+(21*e1*e1/16-55*Math.pow(e1,4)/32)*Math.sin(4*mu)+(151*Math.pow(e1,3)/96)*Math.sin(6*mu);const N=a/Math.sqrt(1-e*Math.sin(p)**2),T=Math.tan(p)**2,C=ep*Math.cos(p)**2,R=a*(1-e)/Math.pow(1-e*Math.sin(p)**2,1.5),D=x/(N*k0);let lat=p-(N*Math.tan(p)/R)*(D**2/2-(5+3*T+10*C-4*C**2-9*ep)*D**4/24+(61+90*T+298*C+45*T**2-252*ep-3*C**2)*D**6/720);lat=lat*180/Math.PI;let lon=(D-(1+2*T+C)*D**3/6+(5-2*C+28*T-3*C**2+8*ep+24*T**2)*D**5/120)/Math.cos(p);lon=lo+lon*180/Math.PI;return[lat,lon]}
function initMap(){map=L.map('map',{zoomControl:true}).setView([-12.218,-76.923],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:22,attribution:'&copy; OpenStreetMap'}).addTo(map);setTimeout(()=>map.invalidateSize(),300)}
function drawData(d){const [lat,lon]=utmToLatLon(Number(d.utmX),Number(d.utmY),Number(d.zone),d.hemisphere),center=L.latLng(lat,lon);[blastMarker,circleEquipos,circlePersonal].forEach(l=>{if(l)map.removeLayer(l)});blastMarker=L.marker(center).addTo(map).bindPopup('Punto de voladura');circleEquipos=L.circle(center,{radius:Number(d.radiusEquipos),color:'red',fillColor:'red',fillOpacity:.16,weight:3}).addTo(map);circlePersonal=L.circle(center,{radius:Number(d.radiusPersonal),color:'lime',fillColor:'lime',fillOpacity:.08,weight:3}).addTo(map);map.fitBounds(circlePersonal.getBounds(),{padding:[25,25]});setTimeout(()=>map.invalidateSize(),300)}
function renderPlan(d){const box=document.getElementById('planContainer');if(!box)return;box.innerHTML='';const url=d.planDataUrl||DEFAULT_PLAN;if((d.planMime||'').includes('pdf')){const f=document.createElement('iframe');f.src=url;box.appendChild(f)}else{const img=document.createElement('img');img.src=url;img.alt='Plano de referencia';box.appendChild(img)}}
function viewerData(d){document.getElementById('vNombre').textContent=d.blastName||'-';document.getElementById('vFechaHora').textContent=(d.date||'-')+' / '+(d.time||'-');document.getElementById('vRadioEq').textContent=(d.radiusEquipos||'-')+' m';document.getElementById('vRadioPe').textContent=(d.radiusPersonal||'-')+' m'}
function evaluar(){if(!userMarker||!circlePersonal)return;const dist=userMarker.getLatLng().distanceTo(circlePersonal.getLatLng()),re=Number(currentData.radiusEquipos),rp=Number(currentData.radiusPersonal),res=document.getElementById('resultado'),det=document.getElementById('detalle');res.className='resultado';if(dist<=rp){res.classList.add('peligro');res.textContent=dist<=re?'🔴 DENTRO DEL RADIO DE EQUIPOS':'🔴 DENTRO DEL RADIO DE PERSONAL'}else{res.classList.add('ok');res.textContent='🟢 FUERA DEL RADIO'}det.textContent='Distancia aproximada: '+Math.round(dist)+' m. Radio equipos: '+re+' m. Radio personal: '+rp+' m.'}
function gps(){if(!navigator.geolocation){alert('Tu navegador no soporta GPS.');return}document.getElementById('resultado').className='resultado neutral';document.getElementById('resultado').textContent='Buscando ubicación GPS...';navigator.geolocation.getCurrentPosition(pos=>{const ll=L.latLng(pos.coords.latitude,pos.coords.longitude);if(userMarker)map.removeLayer(userMarker);userMarker=L.circleMarker(ll,{radius:9,color:'#2563eb',fillColor:'#2563eb',fillOpacity:.95}).addTo(map).bindPopup('Mi ubicación GPS').openPopup();evaluar();map.fitBounds(L.featureGroup([blastMarker,userMarker,circlePersonal]).getBounds(),{padding:[35,35]});document.getElementById('map').scrollIntoView({behavior:'smooth',block:'center'})},err=>{document.getElementById('resultado').className='resultado peligro';document.getElementById('resultado').textContent='No se pudo obtener la ubicación.';document.getElementById('detalle').textContent='Revisa permisos de GPS y HTTPS.'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
function adminData(){return{blastName:document.getElementById('blastName').value,utmX:Number(document.getElementById('utmX').value),utmY:Number(document.getElementById('utmY').value),zone:Number(document.getElementById('zone').value),hemisphere:document.getElementById('hemisphere').value,radiusEquipos:Number(document.getElementById('radiusEquipos').value),radiusPersonal:Number(document.getElementById('radiusPersonal').value),date:document.getElementById('date').value,time:document.getElementById('time').value,planDataUrl:selectedPlanUrl,planMime:selectedPlanMime||'image/png'}}
let selectedPlanMime='image/png';
function setAdminDefaults(){const d=DEFAULT_DATA;currentData=d;['blastName','utmX','utmY','zone','radiusEquipos','radiusPersonal','date','time'].forEach(id=>document.getElementById(id).value=d[id]);document.getElementById('hemisphere').value=d.hemisphere}
function preview(){currentData=adminData();drawData(currentData);renderPlan(currentData)}
function readAsDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
function compressImage(file,maxW=850,quality=.45){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{const s=Math.min(1,maxW/img.width),w=Math.round(img.width*s),h=Math.round(img.height*s);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function handleFile(e){const f=e.target.files[0];if(!f)return;selectedPlanMime=f.type;if(f.type.includes('pdf')){selectedPlanUrl=await readAsDataUrl(f)}else{selectedPlanUrl=await compressImage(f)}preview()}
function generateLink(){currentData=adminData();const base=location.href.replace(/admin\.html.*/,'index.html').replace(/\#.*/,'');const link=base+'#data='+enc(currentData);document.getElementById('publicLink').value=link;if(link.length>18000)alert('El enlace puede ser muy largo. Usa una captura más liviana del plano.')}
async function copyLink(){const val=document.getElementById('publicLink').value;if(!val){alert('Primero genera el enlace.');return}try{await navigator.clipboard.writeText(val);alert('Enlace copiado.')}catch(e){alert('Copia manualmente el enlace.')}}
function boot(){initMap();if(document.body.dataset.mode==='admin'){document.getElementById('date').value=new Date().toISOString().slice(0,10);setAdminDefaults();drawData(currentData);renderPlan(currentData);document.getElementById('planFile').addEventListener('change',handleFile);document.getElementById('btnPreview').addEventListener('click',preview);document.getElementById('btnGenerate').addEventListener('click',generateLink);document.getElementById('btnCopy').addEventListener('click',copyLink)}else{currentData=dataFromHash();viewerData(currentData);drawData(currentData);renderPlan(currentData);document.getElementById('btnGPS').addEventListener('click',gps)}}
window.addEventListener('load',boot);window.addEventListener('resize',()=>map&&map.invalidateSize())